spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
  session:
    store-type: none
  output:
    ansi:
      enabled: ALWAYS
  redis:
    host: 123.207.233.85
server:
  port: 8060
#security:
#  basic:
#    enabled: false
#com:
#  ldb:
#    browser:
#      loginPage: /demo-signIn.html
#com:
#  ldb:
#    browser:
#     loginType: REDIRECT
com:
  ldb:
    code:
      image:
        length: 6
        width: 100
        url: /user,/user/*