spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
  session:
    store-type: none
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 8060
security:
  basic:
    enabled: false
